### ISSUE TITLE
Demos not running

### ISSUE THREAD

**Issue by fotisz** [aslanides/aixijs#14]
Hi there, 

I have tried to run the demos but they don't seem to run ... is it a dead link?

**Comment by aslanides** [comment]
@fotisz are you running on Chrome? They're working fine for me.

**Comment by fotisz** [comment]
@aslanides yes I am on Chrome, attaching screenshot after pressing run below:

![image](https://cloud.githubusercontent.com/assets/7210372/21713935/5ed761e4-d3f4-11e6-84fc-fa74e480c855.png)

**Comment by aslanides** [comment]
Hmm, thanks for the heads up. I won't be at the computer for a couple of days, but I'll look at it again early next week and figure it out then. Cheers 👍

**Comment by fotisz** [comment]
That's great, I'd definitely like to see it action!

**Comment by aslanides** [comment]
Hi @fotisz. Sorry for taking so long to get back to you! Could you tell me what version of Chrome you're running?

**Comment by fotisz** [comment]
55.0.2883.95

**Comment by aslanides** [comment]
Hmm, that's strange; that version should work. Do any errors appear in your JS console after you hit run?

**Comment by fotisz** [comment]
Uncaught Type Error: mds[Symbol.iterator] is not a function ui.js;24
Uncaught Type Error: div.children[Symbol.iterator] is not a function ui.js:182

**Comment by aslanides** [comment]
Hmm, it's really strange that I can't reproduce this. That error is symptomatic of a browser that doesn't support `for ... of` -- but you're running Chrome 55, so that can't be it. All I can suggest for now is to clone it locally and try making changes to `ui.js:24` and `ui.js:182` along the lines of [this StackOverflow question](http://stackoverflow.com/questions/37676768/symbol-iterator-is-not-a-function). Let me know if that helps.

**Comment by fotisz** [comment]
True, tried on another laptop and not getting any errors ... Closing this one down. Many thanks for your help!
